name: Run ESLint on Pull Requests

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: 'aaa'
        required: true
        description: 'Branch'
      config:
        type: string
        default: 'app-dev3'
        required: true
        description: 'Use config'

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:

      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install your dependencies
      - run: npm i
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      # Run ESLint
      - run: npm run lint
