name: Run ESLint on Pull Requests

on:
  - pull_request

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:

      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # Install your dependencies
      - run: npm i @babel/eslint-parser eslint eslint-config-airbnb eslint-plugin-babel eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks ncp

      # Run ESLint
      - run: npm run lint
